### ISSUE TITLE
Server response does not contain "Content-Encoding: br"

### ISSUE THREAD

**Issue by VirtualZer0** [BlueMap-Minecraft/BlueMapBrotli#4]
After installing this plugin and completely removing and re-rendering the map, I decided to check how effectively this plugin works. In the server response, .prbm files do not contain a Content-Encoding header at all, and map loading is incredibly slow. I'm not sure if the plugin works at all, or if it only works on the storage side, repacking data before sending it to client. In the settings I set compression: "bluemap-brotli:brotli-9".

I used BlueMap 5.3 and plugin version 1.1, and my browser support Brotli and sends correct Accept-Encoding header.

If the plugin doesn't support serving Brotli-compressed data to the client, I'd like to see that option available.

**Comment by TBlueF** [comment]
How are you hosting your webapp? If you are using an external webserver like nginx or apache, then you'll need to configure the correct content-encoding there

Edit: If you are using the integrated webserver, you will need to reverseproxy it to add `https` .. brotil is only supported via `https` and bluemap's integrated webserver does not support ssl

**Comment by TBlueF** [comment]
Maybe you want to join our [discord](https://discord.gg/zmkyJa3) and we can check out your issue over there? :)

**Comment by TBlueF** [comment]
Closing, as this seems to be a setup issue and there was no further response :)

**Comment by VirtualZer0** [comment]
@TBlueF sorry, I've been a little busy. No, I was using the internal BlueMap web server. It seemed logical to me that it should then automatically configure itself to pass headers. So this plugin only works when proxying through nginx?

**Comment by TBlueF** [comment]
@VirtualZer0 The headers are not the problem .. even if the Webserver would send the br- compressed file with the correct header, if the connection is via http and not https, [your browser will not accept it.](https://stackoverflow.com/questions/43862412/why-is-brotli-not-supported-on-http)
So yes, this addon will only be useful if you reverseproxy or do something else to add SSL :)
